<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cls.proto

namespace GPBMetadata;

class Cls
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0acc020a09636c732e70726f746f1203636c73225e0a034c6f67120c0a04" .
            "74696d6518012001280312220a08636f6e74656e747318022003280b3210" .
            "2e636c732e4c6f672e436f6e74656e741a250a07436f6e74656e74120b0a" .
            "036b6579180120012809120d0a0576616c756518022001280922240a064c" .
            "6f67546167120b0a036b6579180120012809120d0a0576616c7565180220" .
            "01280922770a084c6f6747726f757012160a046c6f677318012003280b32" .
            "082e636c732e4c6f6712130a0b636f6e74657874466c6f77180220012809" .
            "12100a0866696c656e616d65180320012809120e0a06736f757263651804" .
            "20012809121c0a076c6f675461677318052003280b320b2e636c732e4c6f" .
            "6754616722330a0c4c6f6747726f75704c69737412230a0c6c6f6747726f" .
            "75704c69737418012003280b320d2e636c732e4c6f6747726f7570620670" .
            "726f746f33"
        ));

        static::$is_initialized = true;
    }
}

